export const EDITORIAL_SCHEDULE = {
  timezone: "America/Sao_Paulo",
  dailyTargetVideos: 8,
  dailyMinimumVideos: 6,
  dailyMaximumVideos: 10,
  weeklyTargetVideos: 56,
  weeklyHighlightShorts: 4,
  dailyHighlightPublication: "07:00",
  dailyHighlightClosing: "23:30-00:00",
  weeklyHighlightPublication: "Sunday 20:00",
  collectionWindows: [
    { label: "madrugada/manhã", start: "05:30", end: "07:00", purpose: "captar o que aconteceu durante a noite e preparar a primeira edição" },
    { label: "manhã", start: "08:30", end: "10:30", purpose: "captar atualizações após o início do expediente" },
    { label: "almoço", start: "11:00", end: "13:30", purpose: "captar fatos com potencial para a janela de maior consumo" },
    { label: "tarde", start: "14:00", end: "17:30", purpose: "acompanhar desdobramentos e preparar a saída do trabalho" },
    { label: "noite", start: "18:00", end: "22:30", purpose: "captar acontecimentos do fim do expediente e do horário de maior navegação" },
    { label: "fechamento", start: "23:30", end: "00:00", purpose: "fechar o Destaque do Dia e consolidar a edição" },
  ],
  publicationWindows: [
    { time: "07:00", role: "abertura", content: "vídeo principal + contexto para quem acorda/começa o deslocamento" },
    { time: "08:30", role: "manhã", content: "atualização relevante" },
    { time: "10:30", role: "pré-almoço", content: "fato/eleição/pesquisa de alta relevância" },
    { time: "12:00", role: "almoço", content: "vídeo de maior potencial de consumo" },
    { time: "13:00", role: "almoço", content: "segundo conteúdo da janela de pausa" },
    { time: "15:30", role: "tarde", content: "contexto ou desdobramento" },
    { time: "18:30", role: "saída do trabalho", content: "acontecimento quente do fim do expediente" },
    { time: "20:30", role: "prime time", content: "vídeo mais forte do período noturno" },
  ],
} as const;
